services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - app-network

volumes:
  jenkins_home:
    driver: local

networks:
  app-network:
    driver: bridge
